Algoritmo "Programação Orientada a Objetos"

tipo
CadastroCliente = registro
  nome : caractere
  rg : caractere
  idade : inteiro
fimregistro

Var

cliente1 : CadastroCliente

Inicio

escreval("Digite o nome: ")
leia(cliente1.nome)
escreval("Digite o rg: ")
leia(cliente1.rg)
escreval("Digite a idade: ")
leia(cliente1.idade)

escreval("O nome do cliente é: ",cliente1.nome, " o rg é: ",cliente1.rg," e a idade é: ",cliente1.idade)
Fimalgoritmo
